show_sidebar = true
pixel_ratio = 2.0

[[databases.databases]]
id = "0c737e63-fa14-4425-90fd-44525b33fa85"
slug = "dql-browser"
connection_type = "Server"
persistence_dir = "/Users/phatblat/tmp/ditto-9ac9c915-111a-4e46-9b60-a4944ec503df"
last_opened = "2025-11-02T22:43:55.500407Z"
auth_provider = "development"
current_query = "SELECT * FROM cars"
query_history = [
    "SELECT * FROM system:all_collections",
    "SELECT * FROM system:collections",
    "SELECT * FROM __feature_flags",
    """insert into cars DOCUMENTS (deserialize_json('{"key":"value"}'))""",
    "SELECT * FROM all_collections",
    "SELECT * FROM cars",
    "SELECT * FROM collections",
    "SELECT * FROM data_sync_info",
]

[[databases.databases]]
id = "e9aefa4f-3a11-4d22-ac9a-d701b49249f2"
connection_type = "SmallPeersOnly"
persistence_dir = "/Users/phatblat/Library/Application Support/rs.com.ditto.dql-browser/new_db"
last_opened = "2025-11-02T23:08:54.295826Z"
current_query = "SELECT * FROM active_requests"
query_history = [
    "SELECT * FROM system:all_collections",
    "SELECT * FROM collections",
    "SELECT * FROM data_sync_info",
    "SELECT * FROM __feature_flags",
    "SELECT * FROM all_collections",
    "SELECT * FROM active_requests",
]
