#
# Starship Config
# https://starship.rs/config/
#

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 1000

[aws]
disabled = false

[battery]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[env_var.MISE_SHELL]
# This works
disabled = false

[gcloud]
disabled = false

[line_break]
disabled = false

[mise]
# This doesn't work
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[shell]
disabled = false

[status]
disabled = true
