#
# ~/.config/mise/config.toml
# https://mise.jdx.dev/configuration.html
#

[tools]
"npm:@linear/cli" = "0.0.5"
"npm:@musistudio/claude-code-router" = "1.0.73"
"npm:ccusage" = "17.2.0"
"npm:mint" = "4.2.249"
"npm:prettier" = "3.7.4"
"npm:yarn" = "1.22.22"
bun = "1.3.5"
direnv = "2.37.1"
docker-cli = "29.1.3"
docker-compose = "5.0.1"
dotnet = "10.0.101"
fd = "10.3.0"
go = "1.25.5"
gradle = "9.2.1"
just = "1.45.0"
node = "24.12.0"
packer = "1.14.3"
python = "3.14.2"
ruby = "3.4.8"
shellcheck = "0.11.0"
shfmt = "3.12.0"
terraform = "1.14.3"
uv = "0.9.18"
ast-grep = "0.40.3"
ripgrep = "15.1.0"
yq = "4.50.1"
actionlint = "1.7.9"
gemini = "0.22.5"
lazygit = "0.57.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "node"]
