#
# ~/.config/mise/config.toml
# https://mise.jdx.dev/configuration.html
#

[tools]
"npm:@linear/cli" = "0.0.5"
"npm:@musistudio/claude-code-router" = "1.0.64"
"npm:@tauri-apps/cli" = "2.9.2"
"npm:ccusage" = "17.1.3"
"npm:mint" = "4.2.186"
"npm:prettier" = "3.6.2"
"npm:yarn" = "1.22.22"
bun = "1.3.1"
direnv = "2.37.1"
dotnet = "9.0.306"
fd = "10.3.0"
go = "1.25.3"
gradle = "9.2.0"
just = "1.43.0"
node = "24.10.0"
packer = "1.14.2"
python = "3.14.0"
ruby = "3.4.7"
shellcheck = "0.11.0"
shfmt = "3.12.0"
terraform = "1.13.4"
uv = "0.9.7"
ast-grep = "0.39.7"
ripgrep = "15.1.0"
yq = "4.48.1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "node"]
