#
# ~/.config/mise/config.toml
# https://mise.jdx.dev/configuration.html
#

[tools]
"npm:@linear/cli" = "0.0.5"
"npm:@musistudio/claude-code-router" = "1.0.68"
"npm:@tauri-apps/cli" = "2.9.4"
"npm:ccusage" = "17.1.6"
"npm:mint" = "4.2.202"
"npm:prettier" = "3.6.2"
"npm:yarn" = "1.22.22"
bun = "1.3.2"
direnv = "2.37.1"
docker-cli = "29.0.1"
docker-compose = "2.40.3"
dotnet = "10.0.100"
fd = "10.3.0"
go = "1.25.4"
gradle = "9.2.0"
just = "1.43.1"
node = "25.2.0"
packer = "1.14.2"
python = "3.14.0"
ruby = "3.4.7"
shellcheck = "0.11.0"
shfmt = "3.12.0"
terraform = "1.13.5"
uv = "0.9.9"
ast-grep = "0.40.0"
ripgrep = "15.1.0"
yq = "4.48.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "node"]
